target 'WaterMe' do
	platform :ios, '11.0'
	use_frameworks!
	
  pod 'SimpleImageViewer', '~> 1.1.1'
	pod 'Crashlytics', '~> 3.10.7'
	pod 'Cheers', '~> 2.1.0'
	pod 'CropViewController', '~> 2.3.6'
	pod 'Result', '~> 4.0.0'
	pod 'RealmSwift', '~> 3.7.6'
	pod 'XCGLogger', '~> 6.0.4'
	pod 'WaterMeData', :path => 'WaterMeData'
	pod 'WaterMeStore', :path => 'WaterMeStore'
end

target 'AdminConsole' do
	platform :ios, '11.0'
	use_frameworks!
	
	pod 'Result'
	pod 'RealmSwift'
	pod 'XCGLogger'
	pod 'WaterMeData', :path => 'WaterMeData'
    pod 'WaterMeStore', :path => 'WaterMeStore'
end

target 'NoDeviceTests' do
	platform :ios, '11.0'
	use_frameworks!
    pod 'WaterMeData', :path => 'WaterMeData'
    pod 'WaterMeStore', :path => 'WaterMeStore'
end

post_install do |installer|

  #
  # Copy Acknowledgements to settings bundle
  #
  require 'fileutils'
  FileUtils.cp_r('Pods/Target Support Files/Pods-WaterMe/Pods-WaterMe-acknowledgements.plist', 'WaterMe/Settings.bundle/Acknowledgements.plist', :remove_destination => true)
  
  #
  # Do Realm Post-Install Hook
  #
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = '4.2'
    end
  end
end