source 'https://cdn.cocoapods.org/'

target 'WaterMe' do
	platform :ios, '11.0'
	use_frameworks!
	
  pod 'SimpleImageViewer', '~> 1.1.1'
	pod 'Cheers', '~> 2.3.0'
	pod 'CropViewController', '~> 2.5.2'
	pod 'RealmSwift', '~> 3.20.0'
	pod 'XCGLogger', '~> 7.0.0'
	pod 'WaterMeData', :path => 'WaterMeData'
	pod 'WaterMeStore', :path => 'WaterMeStore'
end

target 'AdminConsole' do
	platform :ios, '11.0'
	use_frameworks!
	
	pod 'RealmSwift'
	pod 'XCGLogger'
	pod 'WaterMeData', :path => 'WaterMeData'
  pod 'WaterMeStore', :path => 'WaterMeStore'
end

target 'NoDeviceTests' do
	platform :ios, '11.0'
	use_frameworks!
  pod 'WaterMeData', :path => 'WaterMeData'
  pod 'WaterMeStore', :path => 'WaterMeStore'
end

post_install do |installer|

  #
  # Copy Acknowledgements to settings bundle
  #
  require 'fileutils'
  FileUtils.cp_r('Pods/Target Support Files/Pods-WaterMe/Pods-WaterMe-acknowledgements.plist', 'WaterMe/Settings.bundle/Acknowledgements.plist', :remove_destination => true)
  
  #
  # Force everything to use Swift 5.1
  #
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = '5.1.1'
    end
  end
end