target 'WaterMe' do
	platform :ios, '11.0'
	use_frameworks!
	
	pod 'Cheers', '~> 2.0.0'
	pod 'CropViewController', '~> 2.3.6'
	pod 'Result', '~> 3.2.2'
	pod 'RealmSwift', '~> 3.0.2'
	pod 'XCGLogger', '~> 6.0.1'
	pod 'WaterMeData', :path => 'WaterMeData'
	pod 'WaterMeStore', :path => 'WaterMeStore'
end

target 'AdminConsole' do
	platform :ios, '11.0'
	use_frameworks!
	
	pod 'Result', '~> 3.2.2'
	pod 'RealmSwift', '~> 3.0.2'
	pod 'XCGLogger', '~> 6.0.1'
	pod 'WaterMeData', :path => 'WaterMeData'
    pod 'WaterMeStore', :path => 'WaterMeStore'
end

target 'NoDeviceTests' do
	platform :ios, '11.0'
	use_frameworks!
    pod 'WaterMeData', :path => 'WaterMeData'
    pod 'WaterMeStore', :path => 'WaterMeStore'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = '4.0.3'
    end
  end
end